### ISSUE TITLE
redirect 404 page

### ISSUE THREAD

**Issue by ryuandrew** [ryuandrew/MemeGenerator#19]
User Story
AS A user
I WANT the 404 page to display when there is an error
SO THAT I know there was an error

Acceptance Criteria:
- [ ] When an error occurs, the 404 page displays

**Comment by jevanson22** [comment]
It looks like all that needs to be done is name the page 404.html and github will direct it by default. Don't know if this justifies a push of it's own, of if we can just make a note of it and tie it into another push later.
