### ISSUE TITLE
Prepare for presenation

### ISSUE THREAD

**Issue by ryuandrew** [ryuandrew/MemeGenerator#32]
- [x] Elevator pitch: a one minute description of the application
- [x] Concept: What is your user story? What was your motivation for development?
- [x] Process: What were the technologies used? How were tasks and roles broken down assigned? What challenges did you encounter? What were your successes?
- [x] Demo
- [x] Directions for future development
- [x] Links to the deployed application and the GitHub repo

**Comment by jevanson22** [comment]
I'll try to make the markdown presentation in time to push it first thing
tomorrow after group review.
